graph TD
  package__ankhorage_supabase_db["@ankhorage/supabase-db"]
  entrypoint_src_index_ts["src/index.ts"]
  package__ankhorage_supabase_db --> entrypoint_src_index_ts
  module_src_index_ts["src/index.ts"]
